"""
===============================================================================
  train_model.py — Train & Export Trading Signal Model to ONNX  (v2)
===============================================================================
  Complete rewrite from v1.  Key improvements:

  1. REAL DATA LOADER
     Loads OHLCV CSVs (from Zerodha Kite / Yahoo Finance / NSE) instead of
     synthetic random-walk data.

  2. CORRECT TIME-SERIES SPLIT
     Never shuffles historical data.  Uses a strict chronological
     train / validation / test split to prevent look-ahead bias.

  3. TRIPLE-BARRIER LABELING
     Labels are generated by the barrier method:
     BUY  (2) — price hits TP before SL within lookahead window
     SELL (0) — price hits SL before TP within lookahead window
     HOLD (1) — neither barrier hit within lookahead window

  4. LIGHTGBM CLASSIFIER
     LightGBM trains 10–50× faster than sklearn GBT and typically achieves
     higher accuracy on tabular financial data.  Falls back to sklearn
     GradientBoostingClassifier if lightgbm is not installed.

  5. CLASS BALANCING
     class_weight='balanced' handles the typical HOLD-heavy distribution.

  6. WALK-FORWARD CROSS-VALIDATION
     Trains on months 1–N, tests on month N+1, slides forward.
     Gives a realistic estimate of out-of-sample performance.

  7. CALIBRATED CONFIDENCE
     CalibratedClassifierCV ensures predict_proba outputs are proper
     probabilities (not just relative scores).

  8. FEATURE ENGINEERING matches FeatureEngine v2 exactly (19 features).

  Usage:
      # With real data CSV:
      python scripts/train_model.py --data data/NIFTY_1min.csv

      # Quick test with synthetic data (not for production):
      python scripts/train_model.py --synthetic

  CSV format expected (Zerodha Kite export):
      date,open,high,low,close,volume
      2024-01-01 09:15:00,19500,19510,19490,19505,12345

  Dependencies:
      pip install lightgbm scikit-learn skl2onnx onnxruntime joblib pandas
===============================================================================
"""

import argparse
import sys
import warnings
from pathlib import Path

import numpy as np
import joblib

warnings.filterwarnings("ignore")

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from core.feature_engine import FeatureEngine, FEATURE_DIM


# ─────────────────────────────────────────────────────────────────────────────
#  DATA LOADING
# ─────────────────────────────────────────────────────────────────────────────

def load_csv_data(csv_path: str) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """
    Load OHLCV data from a CSV file.

    Expects columns: date, open, high, low, close, volume
    Optional columns: oi (open interest)

    Returns:
        prices:  (N,) array of close prices
        volumes: (N,) array of volumes
        oi_arr:  (N,) array of open interest (zeros if not present)
    """
    import pandas as pd

    print(f"📂 Loading data from: {csv_path}")
    df = pd.read_csv(csv_path, parse_dates=["date"])
    df = df.sort_values("date").reset_index(drop=True)

    required = {"close", "volume"}
    missing = required - set(df.columns)
    if missing:
        raise ValueError(f"CSV missing required columns: {missing}")

    prices  = df["close"].values.astype(np.float64)
    volumes = df["volume"].values.astype(np.float64)
    oi_arr  = df["oi"].values.astype(np.float64) if "oi" in df.columns else np.zeros_like(prices)

    print(f"   ✅ Loaded {len(prices):,} bars | "
          f"Range: {df['date'].iloc[0]} → {df['date'].iloc[-1]}")
    return prices, volumes, oi_arr


def generate_synthetic_data(
    n_samples: int = 15_000,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """
    Synthetic data for quick testing only.
    NOT for production model training.
    """
    print("⚠️  Using SYNTHETIC data — replace with real OHLCV CSV for production!")
    np.random.seed(42)

    # Simulate a mean-reverting + trending price series
    returns = np.random.normal(0.0001, 0.005, n_samples + 300)
    prices  = 19_500 * np.cumprod(1 + returns)
    volumes = np.abs(np.random.normal(500_000, 150_000, len(prices)))
    oi_arr  = np.abs(np.random.normal(1_000_000, 200_000, len(prices)))

    return prices, volumes, oi_arr


# ─────────────────────────────────────────────────────────────────────────────
#  FEATURE EXTRACTION
# ─────────────────────────────────────────────────────────────────────────────

def extract_features(
    prices: np.ndarray,
    volumes: np.ndarray,
    oi_arr: np.ndarray,
) -> tuple[np.ndarray, np.ndarray]:
    """
    Run each bar through FeatureEngine v2 to produce the training feature matrix.

    FeatureEngine requires full tick dicts.  For OHLCV bars we approximate:
      ltp    = close price
      volume = cumulative volume (same as OHLCV volume field)
      oi     = open interest (if available)
      bid    = close - 0.05 (half-tick approximation)
      ask    = close + 0.05

    Returns:
        features:     (M, 19) float32 array  (M ≤ N after warm-up)
        price_at_bar: (M,)    float64 array  (corresponding close prices)
    """
    print("⚙️  Extracting features via FeatureEngine v2...")

    engine = FeatureEngine(
        rsi_period=14, macd_fast=12, macd_slow=26, macd_signal=9,
        bollinger_period=20, bollinger_std_dev=2.0,
        atr_period=14, vwap_period=20, streak_max=10,
    )

    features_list = []
    prices_out    = []

    for i, (price, vol, oi) in enumerate(zip(prices, volumes, oi_arr)):
        tick = {
            "ltp":    price,
            "volume": vol,
            "oi":     oi,
            "bid":    price - 0.05,
            "ask":    price + 0.05,
        }
        feat = engine.update(tick)
        if feat is not None:
            features_list.append(feat.copy())
            prices_out.append(price)

    features    = np.array(features_list, dtype=np.float32)
    prices_out  = np.array(prices_out, dtype=np.float64)

    print(f"   ✅ {len(features):,} samples with {features.shape[1]} features "
          f"(warm-up discarded {len(prices) - len(features)} bars)")
    return features, prices_out


# ─────────────────────────────────────────────────────────────────────────────
#  TRIPLE-BARRIER LABELING
# ─────────────────────────────────────────────────────────────────────────────

def triple_barrier_labels(
    prices: np.ndarray,
    tp_pct: float = 0.5,
    sl_pct: float = 0.5,
    lookahead: int = 10,
) -> np.ndarray:
    """
    Generate labels using the triple-barrier method.

    For each bar i, scan the next `lookahead` bars:
    • If price hits TP (+tp_pct%) first → label = 2 (BUY)
    • If price hits SL (-sl_pct%) first → label = 0 (SELL)
    • If neither barrier hit          → label = 1 (HOLD)

    This aligns training labels with the actual trade outcomes the bot
    will experience in live execution (same SL/TP percentages).

    Args:
        prices:    Array of close prices corresponding to each feature row.
        tp_pct:    Take-profit threshold (%).
        sl_pct:    Stop-loss threshold (%).
        lookahead: Maximum bars to look forward.

    Returns:
        labels: (N,) int64 array of {0, 1, 2}.
    """
    n = len(prices)
    labels = np.ones(n, dtype=np.int64)  # default: HOLD

    for i in range(n - lookahead):
        entry = prices[i]
        tp    = entry * (1.0 + tp_pct / 100.0)
        sl    = entry * (1.0 - sl_pct / 100.0)

        for j in range(i + 1, min(i + lookahead + 1, n)):
            p = prices[j]
            if p >= tp:
                labels[i] = 2   # BUY — TP hit first
                break
            if p <= sl:
                labels[i] = 0   # SELL — SL hit first
                break

    return labels


# ─────────────────────────────────────────────────────────────────────────────
#  WALK-FORWARD CROSS-VALIDATION
# ─────────────────────────────────────────────────────────────────────────────

def walk_forward_cv(
    X: np.ndarray,
    y: np.ndarray,
    n_splits: int = 5,
) -> list[dict]:
    """
    Time-series walk-forward cross-validation.

    Splits the data into (n_splits + 1) equal blocks.
    Fold k trains on blocks 0..k and tests on block k+1.

    Returns:
        List of dicts with keys: fold, train_size, test_size, accuracy,
        buy_precision, sell_precision.
    """
    try:
        import lightgbm as lgb
        ModelClass = lgb.LGBMClassifier
        model_kwargs = dict(
            n_estimators=200, max_depth=6, learning_rate=0.05,
            class_weight="balanced", n_jobs=1, random_state=42,
            verbose=-1,
        )
    except ImportError:
        from sklearn.ensemble import GradientBoostingClassifier
        ModelClass = GradientBoostingClassifier
        model_kwargs = dict(
            n_estimators=100, max_depth=4, learning_rate=0.1,
            random_state=42,
        )

    from sklearn.preprocessing import StandardScaler
    from sklearn.metrics import accuracy_score, precision_score

    n = len(X)
    block = n // (n_splits + 1)
    results = []

    print(f"\n🔄 Walk-forward CV ({n_splits} folds, block size ≈ {block:,} bars)...")

    for fold in range(1, n_splits + 1):
        train_end = fold * block
        test_end  = min((fold + 1) * block, n)

        X_tr, y_tr = X[:train_end],           y[:train_end]
        X_te, y_te = X[train_end:test_end],   y[train_end:test_end]

        scaler   = StandardScaler()
        X_tr_sc  = scaler.fit_transform(X_tr)
        X_te_sc  = scaler.transform(X_te)

        model = ModelClass(**model_kwargs)
        model.fit(X_tr_sc, y_tr)

        y_pred = model.predict(X_te_sc)
        acc    = accuracy_score(y_te, y_pred)

        # Per-class precision for BUY and SELL (classes 2 and 0)
        prec = precision_score(
            y_te, y_pred, labels=[0, 2], average=None,
            zero_division=0,
        )

        results.append({
            "fold":           fold,
            "train_size":     len(X_tr),
            "test_size":      len(X_te),
            "accuracy":       round(acc, 4),
            "sell_precision": round(float(prec[0]), 4),
            "buy_precision":  round(float(prec[1]), 4),
        })
        print(
            f"   Fold {fold}/{n_splits} | "
            f"Train: {len(X_tr):,} | Test: {len(X_te):,} | "
            f"Acc: {acc:.2%} | "
            f"BUY prec: {float(prec[1]):.2%} | "
            f"SELL prec: {float(prec[0]):.2%}"
        )

    avg_acc = np.mean([r["accuracy"] for r in results])
    print(f"   Mean CV accuracy: {avg_acc:.2%}")
    return results


# ─────────────────────────────────────────────────────────────────────────────
#  TRAIN AND EXPORT
# ─────────────────────────────────────────────────────────────────────────────

def train_and_export(
    csv_path: str | None = None,
    synthetic: bool = False,
    tp_pct: float = 0.5,
    sl_pct: float = 0.5,
    lookahead: int = 10,
    test_pct: float = 0.15,
    val_pct: float = 0.10,
) -> None:
    """
    Full training pipeline.

    Split strategy (chronological — NO shuffle):
        |──────────────────────────────|──────────|──────────|
        │    train (75 %)              │  val     │  test    │
        │                              │  (10 %)  │  (15 %)  │
        └──────────────────────────────┴──────────┴──────────┘
    """
    from sklearn.preprocessing import StandardScaler
    from sklearn.metrics import classification_report, accuracy_score

    # ── Step 1: Load / generate data ─────────────────────────────────────
    if synthetic or csv_path is None:
        prices, volumes, oi_arr = generate_synthetic_data()
    else:
        prices, volumes, oi_arr = load_csv_data(csv_path)

    # ── Step 2: Extract features ──────────────────────────────────────────
    features, feat_prices = extract_features(prices, volumes, oi_arr)

    # ── Step 3: Generate triple-barrier labels ────────────────────────────
    print(f"\n🏷️  Triple-barrier labeling | TP={tp_pct}% SL={sl_pct}% lookahead={lookahead}")
    labels = triple_barrier_labels(feat_prices, tp_pct, sl_pct, lookahead)

    # Trim the last `lookahead` rows (no future data)
    features = features[:-lookahead]
    labels   = labels[:-lookahead]

    unique, counts = np.unique(labels, return_counts=True)
    dist = dict(zip(["SELL", "HOLD", "BUY"], counts))
    print(f"   Label distribution: {dist}")

    # ── Step 4: Chronological split (NO shuffle) ──────────────────────────
    n        = len(features)
    val_idx  = int(n * (1.0 - val_pct - test_pct))
    test_idx = int(n * (1.0 - test_pct))

    X_train, y_train = features[:val_idx],        labels[:val_idx]
    X_val,   y_val   = features[val_idx:test_idx], labels[val_idx:test_idx]
    X_test,  y_test  = features[test_idx:],        labels[test_idx:]

    print(
        f"\n📐 Split | Train: {len(X_train):,} | "
        f"Val: {len(X_val):,} | Test: {len(X_test):,}"
    )

    # ── Step 5: Scale features ────────────────────────────────────────────
    scaler      = StandardScaler()
    X_train_sc  = scaler.fit_transform(X_train)
    X_val_sc    = scaler.transform(X_val)
    X_test_sc   = scaler.transform(X_test)

    # ── Step 6: Walk-forward CV on training set ───────────────────────────
    walk_forward_cv(X_train, y_train, n_splits=5)

    # ── Step 7: Train final model on train + val ──────────────────────────
    print("\n🏋️  Training final model on train + val...")

    X_full   = np.vstack([X_train_sc, X_val_sc])
    y_full   = np.concatenate([y_train, y_val])

    try:
        import lightgbm as lgb
        print("   Using LightGBM classifier")
        base_model = lgb.LGBMClassifier(
            n_estimators=300,
            max_depth=6,
            learning_rate=0.05,
            num_leaves=63,
            min_child_samples=20,
            subsample=0.8,
            colsample_bytree=0.8,
            class_weight="balanced",
            n_jobs=1,
            random_state=42,
            verbose=-1,
        )
    except ImportError:
        print("   LightGBM not installed — using GradientBoostingClassifier")
        print("   Install with: pip install lightgbm")
        from sklearn.ensemble import GradientBoostingClassifier
        from sklearn.utils.class_weight import compute_sample_weight
        base_model = GradientBoostingClassifier(
            n_estimators=200,
            max_depth=5,
            learning_rate=0.05,
            subsample=0.8,
            random_state=42,
        )

    base_model.fit(X_full, y_full)

    # ── Step 8: Calibrate probabilities ──────────────────────────────────
    from sklearn.calibration import CalibratedClassifierCV

    print("   Calibrating probabilities (isotonic regression)...")
    # Calibrate on the validation set only (already scaled)
    model = CalibratedClassifierCV(base_model, cv="prefit", method="isotonic")
    model.fit(X_val_sc, y_val)

    # ── Step 9: Evaluate on held-out test set ─────────────────────────────
    y_pred   = model.predict(X_test_sc)
    accuracy = accuracy_score(y_test, y_pred)

    print(f"\n📋 Test set classification report:")
    print(classification_report(y_test, y_pred, target_names=["SELL", "HOLD", "BUY"]))
    print(f"   Test accuracy: {accuracy:.2%}")

    # ── Step 10: Export to ONNX ───────────────────────────────────────────
    print("\n📦 Exporting to ONNX...")
    try:
        from skl2onnx import convert_sklearn
        from skl2onnx.common.data_types import FloatTensorType

        initial_type = [("input", FloatTensorType([None, X_train.shape[1]]))]
        onnx_model = convert_sklearn(
            model,
            initial_types=initial_type,
            target_opset=13,
            options={type(base_model): {"zipmap": False}},
        )

        model_path = PROJECT_ROOT / "models" / "model.onnx"
        model_path.write_bytes(onnx_model.SerializeToString())
        print(f"   ✅ ONNX model → {model_path} ({model_path.stat().st_size / 1024:.1f} KB)")

    except ImportError:
        print("   ❌ skl2onnx not installed: pip install skl2onnx")
        return

    # ── Step 11: Save scaler ──────────────────────────────────────────────
    scaler_path = PROJECT_ROOT / "models" / "scaler.pkl"
    joblib.dump(scaler, scaler_path)
    print(f"   ✅ Scaler → {scaler_path}")

    # ── Step 12: Verify ONNX model ────────────────────────────────────────
    print("\n🔍 Verifying ONNX model...")
    import onnxruntime as ort

    sess = ort.InferenceSession(str(model_path), providers=["CPUExecutionProvider"])
    inp  = sess.get_inputs()[0].name
    out  = sess.get_outputs()[0].name

    sample = scaler.transform(X_test[:1]).astype(np.float32)
    result = sess.run([out], {inp: sample})
    print(f"   Input shape:  {sample.shape}")
    print(f"   Output shape: {result[0].shape}")
    print(f"   Sample probs: {result[0][0].round(4)}")
    print(f"   ✅ ONNX model verified!")

    # ── Summary ──────────────────────────────────────────────────────────
    print("\n" + "=" * 60)
    print("  🎉 TRAINING COMPLETE")
    print("=" * 60)
    print(f"  Features:  {X_train.shape[1]} (FeatureEngine v2)")
    print(f"  Model:     models/model.onnx ({model_path.stat().st_size/1024:.1f} KB)")
    print(f"  Scaler:    models/scaler.pkl")
    print(f"  Test acc:  {accuracy:.2%}")
    print(f"  Labeling:  Triple-barrier TP={tp_pct}% SL={sl_pct}% look={lookahead}")
    print()
    print("  Next: python main.py")
    print("=" * 60)


# ─────────────────────────────────────────────────────────────────────────────
#  CLI
# ─────────────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Train HFT model v2")
    parser.add_argument(
        "--data", type=str, default=None,
        help="Path to OHLCV CSV file (date,open,high,low,close,volume[,oi])"
    )
    parser.add_argument(
        "--synthetic", action="store_true",
        help="Use synthetic data (testing only, not for production)"
    )
    parser.add_argument("--tp",         type=float, default=0.5,  help="Take-profit %")
    parser.add_argument("--sl",         type=float, default=0.5,  help="Stop-loss %")
    parser.add_argument("--lookahead",  type=int,   default=10,   help="Barrier lookahead bars")
    parser.add_argument("--test-pct",   type=float, default=0.15, help="Test set fraction")
    parser.add_argument("--val-pct",    type=float, default=0.10, help="Validation set fraction")
    args = parser.parse_args()

    if args.data is None and not args.synthetic:
        print("⚠️  No --data path provided.  Using --synthetic data.")
        print("    For production: python scripts/train_model.py --data path/to/data.csv")
        args.synthetic = True

    train_and_export(
        csv_path=args.data,
        synthetic=args.synthetic,
        tp_pct=args.tp,
        sl_pct=args.sl,
        lookahead=args.lookahead,
        test_pct=args.test_pct,
        val_pct=args.val_pct,
    )
